# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 23:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('injury', models.TextField(blank=True, null=True)),
                ('minutes', models.FloatField()),
                ('money_line', models.IntegerField()),
                ('opponent', models.CharField(max_length=50)),
                ('over_under', models.FloatField()),
                ('point_spread', models.FloatField()),
                ('position', models.CharField(max_length=50)),
                ('proj_ceiling', models.FloatField()),
                ('proj_custom', models.FloatField()),
                ('proj_floor', models.FloatField()),
                ('proj_original', models.FloatField()),
                ('proj_points', models.FloatField()),
                ('proj_rotowire', models.FloatField()),
                ('proj_site', models.FloatField()),
                ('proj_third_party_one', models.FloatField()),
                ('proj_third_party_two', models.FloatField()),
                ('real_position', models.CharField(blank=True, max_length=50, null=True)),
                ('salary', models.FloatField()),
                ('salary_custom', models.FloatField()),
                ('salary_original', models.FloatField()),
                ('team', models.CharField(max_length=50)),
                ('team_points', models.FloatField()),
                ('value', models.FloatField()),
                ('data_source', models.CharField(choices=[('FanDuel', 'FanDuel'), ('DraftKings', 'DraftKings'), ('Yahoo', 'Yahoo'), ('Head2Head', 'Head2Head'), ('Fanball', 'Fanball'), ('FantasyDraft', 'FantasyDraft')], default='FanDuel', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
