# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-11 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_playergame'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='avatar',
            field=models.CharField(default='/static/img/nba.ico', max_length=250),
        ),
    ]
