# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-23 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0003_player_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_team', models.CharField(max_length=20)),
                ('visit_team', models.CharField(max_length=20)),
                ('home_logo', models.CharField(blank=True, max_length=120, null=True)),
                ('visit_logo', models.CharField(blank=True, max_length=120, null=True)),
                ('ou', models.FloatField()),
                ('ml', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('game_status', models.CharField(choices=[('started', 'Started'), ('upcomming', 'Upcomming')], default='started', max_length=50)),
                ('slate', models.CharField(choices=[('Thu-Mon', 'Thu-Mon'), ('Express', 'Express'), ('Main', 'Main')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='player',
            name='data_source',
            field=models.CharField(choices=[('FanDuel', 'FanDuel'), ('DraftKings', 'DraftKings'), ('Yahoo', 'Yahoo'), ('Fanball', 'Fanball')], default='FanDuel', max_length=30),
        ),
    ]
