# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-30 08:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0004_auto_20180923_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='data_source',
            field=models.CharField(choices=[('FanDuel', 'FanDuel'), ('DraftKings', 'DraftKings'), ('Yahoo', 'Yahoo'), ('Head2Head', 'Head2Head'), ('Fanball', 'Fanball'), ('FantasyDraft', 'FantasyDraft')], default='FanDuel', max_length=30),
        ),
    ]
