# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-03 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_tmscache'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavPlayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.Player')),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='slate',
        ),
    ]
