# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-06 11:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0007_auto_20181003_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='real_position',
        ),
        migrations.AddField(
            model_name='player',
            name='actual_position',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='player',
            name='injury',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
