# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-03 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0009_auto_20181013_2104'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='home_logo',
        ),
        migrations.RemoveField(
            model_name='game',
            name='visit_logo',
        ),
        migrations.AddField(
            model_name='player',
            name='play_today',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='data_source',
            field=models.CharField(choices=[('FanDuel', 'FanDuel'), ('DraftKings', 'DraftKings'), ('Yahoo', 'Yahoo'), ('Fanball', 'Fanball')], default='FanDuel', max_length=30),
        ),
    ]
