# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-10-19 17:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0011_auto_20181210_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='money_line',
        ),
        migrations.RemoveField(
            model_name='player',
            name='point_spread',
        ),
        migrations.RemoveField(
            model_name='player',
            name='proj_ceiling',
        ),
        migrations.RemoveField(
            model_name='player',
            name='proj_custom',
        ),
        migrations.RemoveField(
            model_name='player',
            name='proj_floor',
        ),
        migrations.RemoveField(
            model_name='player',
            name='proj_original',
        ),
        migrations.RemoveField(
            model_name='player',
            name='proj_rotowire',
        ),
        migrations.RemoveField(
            model_name='player',
            name='proj_third_party_one',
        ),
        migrations.RemoveField(
            model_name='player',
            name='proj_third_party_two',
        ),
        migrations.RemoveField(
            model_name='player',
            name='team_points',
        ),
    ]
