# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-10-19 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0012_auto_20211019_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='salary_custom',
            new_name='afp',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='minutes',
            new_name='ampg',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='salary_original',
            new_name='l3a',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='proj_site',
            new_name='sfp',
        ),
        migrations.RenameField(
            model_name='player',
            old_name='over_under',
            new_name='smpg',
        ),
    ]
