# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2021-10-19 18:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0013_auto_20211019_1721'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='game_status',
        ),
    ]
